services:
  pds:
    image: ghcr.io/bluesky-social/pds:latest
    ports:
      - "3000:3000"
    environment:
      - PDS_HOSTNAME=localhost
      - PDS_JWT_SECRET=atchess-dev-jwt-secret-change-in-production
      - PDS_ADMIN_PASSWORD=admin
      - PDS_INVITE_REQUIRED=false
      - PDS_EMAIL_SMTP_URL=smtp://fake
      - PDS_EMAIL_FROM_ADDRESS=noreply@localhost
      - PDS_DATA_DIRECTORY=/pds
      - PDS_BLOBSTORE_DISK_LOCATION=/pds/blocks
      - PDS_DID_PLC_URL=https://plc.directory
      - PDS_BSKY_APP_VIEW_URL=https://api.bsky.app
      - PDS_BSKY_APP_VIEW_DID=did:web:api.bsky.app
      - PDS_CRAWLERS=https://bsky.network
      - LOG_ENABLED=true
      # Required security keys
      - PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
      - PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX=abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
      # Fix OAuth validation for local development
      - PDS_ENTRYWAY_DID=did:web:localhost%3A3000
      - PDS_ENTRYWAY_URL=http://localhost:3000
      - PDS_ENTRYWAY_JWT_VERIFY_KEY_K256_PUBLIC_KEY_HEX=04b678a0d8c7f3e9a1b2c4d5e6f789012345678901234567890123456789abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
    volumes:
      - pds-data:/pds
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/_health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  pds-data:
    driver: local