services:
  pds:
    image: ghcr.io/bluesky-social/pds:latest
    ports:
      - "3000:3000"
    environment:
      - PDS_HOSTNAME=localhost:3000
      - PDS_JWT_SECRET=your-secret-key-here-change-in-production
      - PDS_ADMIN_PASSWORD=admin
      - PDS_INVITE_REQUIRED=false
      - PDS_EMAIL_SMTP_URL=smtp://fake
      - PDS_EMAIL_FROM_ADDRESS=noreply@localhost
      - PDS_DATA_DIRECTORY=/pds
      - PDS_BLOBSTORE_DISK_LOCATION=/pds/blocks
      - PDS_DID_PLC_URL=https://plc.directory
      - PDS_BSKY_APP_VIEW_URL=https://api.bsky.app
      - PDS_BSKY_APP_VIEW_DID=did:web:api.bsky.app
      - PDS_CRAWLERS=https://bsky.network
      - LOG_ENABLED=true
    volumes:
      - pds-data:/pds
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/_health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  pds-data:
    driver: local