name: Deploy to abrah.ms

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GO_VERSION: '1.21'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Build binaries
      run: |
        # Build protocol service with static linking
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o atchess-protocol ./cmd/protocol
        
        # Build web service with static linking
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o atchess-web ./cmd/web
        
        # Make binaries executable
        chmod +x atchess-protocol atchess-web
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -H -p ${{ secrets.DEPLOY_PORT || 22 }} ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST || 'abrah.ms' }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER || 'atchess-deploy' }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT || 22 }}
      run: |
        # Copy binaries
        scp -i ~/.ssh/deploy_key -P $DEPLOY_PORT \
          atchess-protocol atchess-web \
          $DEPLOY_USER@$DEPLOY_HOST:/tmp/
        
        # Skip wrapper script - not needed
        
        # Copy static files (without timestamps to avoid permission issues)
        tar czf static.tar.gz --mtime='@0' --owner=0 --group=0 -C web static
        scp -i ~/.ssh/deploy_key -P $DEPLOY_PORT \
          static.tar.gz \
          $DEPLOY_USER@$DEPLOY_HOST:/tmp/
        
        # Systemd service files are installed during initial setup only
        
        # Deploy and restart services
        ssh -i ~/.ssh/deploy_key -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_HOST << 'ENDSSH'
          set -e
          
          # Stop services before updating binaries (using sudo - allowed in sudoers)
          echo "Stopping services..."
          sudo systemctl stop atchess-protocol || true
          sudo systemctl stop atchess-web || true
          
          # Wait for services to fully stop
          sleep 2
          
          # Move binaries to a staging area with group permissions
          STAGING_DIR="/srv/atchess/staging"
          mkdir -p "$STAGING_DIR"
          
          # Copy new binaries to staging (we can write here)
          cp /tmp/atchess-protocol /tmp/atchess-web "$STAGING_DIR/"
          chmod +x "$STAGING_DIR"/atchess-*
          
          # Move binaries from staging to app directory
          # Since we're in the atchess group, we should be able to write if permissions are correct
          mv -f "$STAGING_DIR"/atchess-protocol /srv/atchess/app/ || {
            echo "ERROR: Cannot write to /srv/atchess/app/"
            echo "Directory permissions:"
            ls -ld /srv/atchess/app/
            echo "Current user groups:"
            id
            exit 1
          }
          mv -f "$STAGING_DIR"/atchess-web /srv/atchess/app/
          
          # Clean up staging
          rmdir "$STAGING_DIR" 2>/dev/null || true
          
          # Extract static files
          cd /srv/atchess/app
          rm -rf web/static 2>/dev/null || true
          mkdir -p web
          
          # Extract directly to web directory
          cd web
          tar xzf /tmp/static.tar.gz
          cd ..
          
          # Clean up temporary files
          rm -f /tmp/atchess-* /tmp/static.tar.gz 2>/dev/null || true
          
          # Restart services using sudo (allowed by sudoers)
          sudo systemctl daemon-reload
          sudo systemctl restart atchess-protocol
          sudo systemctl restart atchess-web
          
          # Check service status
          sleep 2
          sudo systemctl status atchess-protocol --no-pager || true
          sudo systemctl status atchess-web --no-pager || true
        ENDSSH
    
    - name: Verify deployment
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST || 'atchess.abrah.ms' }}
      run: |
        # Wait for services to start
        echo "Waiting for services to start..."
        sleep 10
        
        # Check health endpoints
        echo "Checking service health..."
        HEALTH_OK=false
        
        # Try the protocol service health endpoint via API path
        if curl -f -s -o /dev/null -w "Protocol health check status: %{http_code}\n" https://$DEPLOY_HOST/api/health; then
          echo "✅ Protocol service health check passed!"
          HEALTH_OK=true
        else
          echo "⚠️  Protocol service health check failed"
        fi
        
        # Try the web service directly
        if curl -f -s -o /dev/null -w "Web service check status: %{http_code}\n" https://$DEPLOY_HOST/; then
          echo "✅ Web service is responding!"
          HEALTH_OK=true
        else
          echo "⚠️  Web service check failed"
        fi
        
        if [ "$HEALTH_OK" = false ]; then
          echo "❌ Both services failed health checks!"
          # Still don't exit with error to allow diagnostics to run
        fi
        
        # Always check service status
        echo "Checking service status on server..."
        ssh -i ~/.ssh/deploy_key -p ${DEPLOY_PORT:-22} ${DEPLOY_USER:-atchess-deploy}@${DEPLOY_HOST:-abrah.ms} << 'ENDSSH'
          echo "=== Checking processes ==="
          ps aux | grep atchess | grep -v grep || true
          echo ""
          echo "=== Checking ports ==="
          netstat -tlnp 2>/dev/null | grep -E ':(8080|8081)' || ss -tlnp 2>/dev/null | grep -E ':(8080|8081)' || true
          echo ""
          echo "=== Checking binaries ==="
          ls -la /srv/atchess/app/atchess-* || true
          echo ""
          echo "=== Checking systemd services (without sudo) ==="
          systemctl status atchess-protocol --no-pager 2>&1 || true
          echo ""
          systemctl status atchess-web --no-pager 2>&1 || true
        ENDSSH
        
        echo ""
        echo "🚀 Deployment complete!"
        echo "ATChess web interface is available at: https://$DEPLOY_HOST"
        echo ""
        echo "⚠️  IMPORTANT: The protocol service requires AT Protocol credentials!"
        echo "   Without valid Bluesky credentials in /etc/atchess/protocol.env,"
        echo "   the protocol service will not start."
        echo ""
        echo "To configure AT Protocol:"
        echo "1. SSH to the server"
        echo "2. Edit /etc/atchess/protocol.env" 
        echo "3. Add your Bluesky handle and app password"
        echo "4. Restart: sudo systemctl restart atchess-protocol"
    
    - name: Clean up SSH
      if: always()
      run: |
        rm -f ~/.ssh/deploy_key